name: 'helmfile-action'
description: 'Install and run Helmfile'
author: 'helmfile'
inputs:
  helmfile-args:
    required: true
    description: 'Helmfile arguments'
  helmfile-version:
    required: false
    description: 'Helmfile version'
    default: 'latest'
  helm-version:
    required: false
    description: 'Helm version'
    default: 'latest'
  helmfile-workdirectory:
    required: false
    description: 'Helmfile working directory'
    default: '.'
  helm-plugins:
    required: false
    description: 'Comma separated list of Helm plugins to install'
    default: 'https://github.com/databus23/helm-diff'
outputs:
  exit-code:
    description: 'Exit code of helmfile. Useful to handle diff --detailed-exitcode'
  helmfile-output:
    description: 'Output of helmfile diff'
  helmfile-error:
    description: 'Error of helmfile'    
runs:
  using: 'node16'
  main: 'dist/index.js'
